
SET SQL DIALECT 3; 

/* CREATE DATABASE 'C:\Users\saulo\Documents\projetosdelphi\projetoCadPessoa\CADPESSOA.FDB' PAGE_SIZE 4096 DEFAULT CHARACTER SET NONE */



/* Table: CIDADE, Owner: SYSDBA */
CREATE TABLE CIDADE (CODIGO INTEGER NOT NULL,
        IBGE VARCHAR(30),
        UF INTEGER,
        ENDERECO INTEGER,
CONSTRAINT PK_CIDADE PRIMARY KEY (CODIGO));

/* Table: ENDERECO, Owner: SYSDBA */
CREATE TABLE ENDERECO (CODIGO INTEGER NOT NULL,
        PESSOA INTEGER,
        CEP VARCHAR(9),
        LOUGRADOURO VARCHAR(100),
        NUMERO VARCHAR(30),
        BAIRRO VARCHAR(100),
        COMPLEMENTO VARCHAR(100),
        CIDADE INTEGER,
        UF INTEGER,
CONSTRAINT PK_ENDERECO PRIMARY KEY (CODIGO));

/* Table: PESSOA, Owner: SYSDBA */
CREATE TABLE PESSOA (CODIGO INTEGER NOT NULL,
        NOME VARCHAR(100),
        NOMEFANTASIA VARCHAR(100),
        CPFCNPJ VARCHAR(18),
        TIPOPESSOA INTEGER,
        EMAIL VARCHAR(100),
        SEXO INTEGER,
        STATUS INTEGER,
CONSTRAINT PK_PESSOA PRIMARY KEY (CODIGO));

/* Table: TELEFONE, Owner: SYSDBA */
CREATE TABLE TELEFONE (CODIGO INTEGER NOT NULL,
        PESSOA INTEGER,
        NUMTELEFONE VARCHAR(15),
        TIPO INTEGER,
CONSTRAINT PK_TELEFONE PRIMARY KEY (CODIGO));

ALTER TABLE CIDADE ADD CONSTRAINT CIDADE_FK FOREIGN KEY (ENDERECO) REFERENCES ENDERECO (CODIGO);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_1 FOREIGN KEY (PESSOA) REFERENCES PESSOA (CODIGO);

ALTER TABLE TELEFONE ADD CONSTRAINT TELEFONE_FK FOREIGN KEY (PESSOA) REFERENCES PESSOA (CODIGO);
